<?xml version="1.0"?>
<package format="3">
  <name>navigation_bringup</name>
  <version>0.1.0</version>
  <description>Minimal FastAnchor, FastPlanner and SCAN-Planner bringup.</description>
  <maintainer email="jhr@example.com">jhr</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>fast_anchor_bringup</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>nav3d_global_planning</exec_depend>
  <exec_depend>pct_global_planner</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>scan_planner</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
