fast_anchor_localization_node:
  ros__parameters:
    map_pcd_path: "maps/map_preprocessed.pcd"
    visualization_map_pcd_path: "maps/map_visualization.pcd"
    icp_map_pcd_path: "maps/map_preprocessed.pcd"

    odom_topic: "/Odometry"
    scan_topic: "/cloud_registered_body"
    initialpose_topic: "/initialpose"

    pose_topic: "icp_pose"
    odom_output_topic: "icp_odom"
    path_topic: "icp_path"
    status_topic: "icp_status"
    icp_result_topic: "icp_result"
    aligned_cloud_topic: "icp_aligned_cloud"
    icp_map_topic: "icp_map"
    visualization_map_topic: "icp_visualization_map"

    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    publish_tf: true
    publish_base_tf: true
    odom_coincident_with_base: true
    publish_map_cloud: true

    base_to_body_xyz: [-0.3, 0.0, -0.2]
    base_to_body_rpy: [0.0, 0.0, 0.0]

    use_initial_pose_param: false
    initial_pose_xyz: [5.93438, 5.90442, 0.0]
    initial_pose_rpy: [0.0, 0.0, 0.0]

    min_range: 0.5
    max_range: 60.0
    scan_leaf_size: 0.25
    map_leaf_size: 0.25
    min_scan_points: 120
    source_non_ground_filter_en: true
    source_non_ground_min_z: -0.2

    max_correspondence_distance: 2.0
    transformation_epsilon: 0.01
    euclidean_fitness_epsilon: 0.01
    max_iterations: 40
    fitness_score_threshold: 2.0
    relocalization_interval_s: 0.2
